version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/accommodation-app
      - JWT_SECRET=your_jwt_secret
      - FIREBASE_PROJECT_ID=your_firebase_project_id
      - FIREBASE_PRIVATE_KEY=your_firebase_private_key
      - FIREBASE_CLIENT_EMAIL=your_firebase_client_email
  mongo:
    image: mongo
    ports:
      - "27017:27017"
